version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/php/laravel_project_table
        volumes:
            - .:/var/php/laravel_project_table
            - ./storage:/var/php/laravel_project_table/storage
        environment:
            - APP_KEY=${APP_KEY}
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - DB_HOST=db
        networks:
            - laravel_network

    webserver:
        image: nginx:stable-alpine
        container_name: nginx_webserver
        restart: unless-stopped
        volumes:
            - .:/var/php/laravel_project_table
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8081:8081"
        environment:
            - APP_ENV=local
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=my_laravel
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3316:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    db_data:
